name: Build WebAssembly Physics Engine

on: 
  push:
    branches: [main]
    paths:
      - 'cpp-code/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 'latest'
    
    - name: Verify Emscripten
      run: |
        emcc --version
        echo "Emscripten ready"
    
    - name: Build WebAssembly Module
  working-directory: ./cpp-code
  run: |
    echo "Compiling C++ to WebAssembly..."

    emcc main.cpp engine.cpp \
      -I./include \
      -o ../docs/physics.js \
      -s WASM=1 \
      -s EXPORTED_RUNTIME_METHODS='["cwrap","ccall"]' \
      -s MODULARIZE=1 \
      -s EXPORT_NAME='createPhysicsModule' \
      -s NO_EXIT_RUNTIME=1 \
      -s ALLOW_MEMORY_GROWTH=1 \
      -s ENVIRONMENT='web' \
      -O3

    ls -lh ../docs/physics.*
        
        echo "WebAssembly build successful!"
        ls -lh physics.js physics.wasm
    
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-physics-engine
        path: |
          cpp-code/physics.js
          cpp-code/physics.wasm
        retention-days: 30
