name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 'latest'
      
      - name: Build WebAssembly Physics Engine
        run: |
          echo "Compiling C++ physics to WebAssembly..."
          cd cpp-code
          
          if grep -q "emscripten.h" main.cpp; then
            echo "Detected Emscripten code, compiling to WASM..."
            
            emcc main.cpp engine.cpp \
              -I./include \
              -o ../website/physics.js \
              -s WASM=1 \
              -s EXPORTED_RUNTIME_METHODS='["cwrap","ccall"]' \
              -s MODULARIZE=1 \
              -s EXPORT_NAME='createPhysicsModule' \
              -s NO_EXIT_RUNTIME=1 \
              -s ALLOW_MEMORY_GROWTH=1 \
              -s ENVIRONMENT='web' \
              -O3
            
            echo "WASM compiled successfully!"
            ls -lh ../website/physics.*
          else
            echo "No Emscripten code detected, skipping WASM build"
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
