% AeroRobotics Verification Script
clear; clc; close all;

% 1. Load Data generated by C++ (Run the C++ exe and pipe to csv first)
% Usage in terminal: ./quad_sim > flight_data.csv
data = readmatrix('flight_data.csv');
t_cpp = data(:,1);
z_cpp = data(:,2);
vz_cpp = data(:,3);

% 2. Define MATLAB Truth Model (ODE45)
mass = 1.0;
g = 9.81;
target = 10.0;
kp = 5.0; kd = 2.5; ki = 0.1;

% Define system dynamics with PID embedded
ode_fun = @(t, state) quad_dynamics(t, state, target, kp, ki, kd, mass, g);

[t_mat, state_mat] = ode45(ode_fun, [0 5], [0; 0; 0]); % State: [z; vz; integral_error]

% 3. Compare Results
figure(1);
subplot(2,1,1);
plot(t_cpp, z_cpp, 'LineWidth', 2); hold on;
plot(t_mat, state_mat(:,1), '--r', 'LineWidth', 2);
title('Altitude: C++ Custom Engine vs MATLAB ODE45');
legend('C++ RK4', 'MATLAB ODE45');
grid on; ylabel('Height (m)');

subplot(2,1,2);
plot(t_cpp, vz_cpp, 'LineWidth', 2);
title('Vertical Velocity');
grid on; ylabel('Vel (m/s)');

% Auxiliary Function
function dxdt = quad_dynamics(t, x, target, kp, ki, kd, m, g)
    z = x(1);
    vz = x(2);
    int_err = x(3);
    
    error = target - z;
    thrust = (kp*error) + (ki*int_err) + (kd*(0 - vz)); % Derivative on measurement
    thrust = max(min(thrust, 20), -20); % Clamp
    
    accel = (thrust / m) - g - (0.1 * vz / m); % Forces
    
    dxdt = [vz; accel; error];
end
